# why numpy... because of screen
Numpy...Numeric Python

In [1]:
l = range(1000000)

In [2]:
%time for i in l:    i*7
    

Wall time: 278 ms


In [4]:
#range returns list while arange returns array.

In [7]:
import numpy as np

In [8]:
l=np.arange(1000000)

In [9]:
%time l*7

Wall time: 0 ns


array([      0,       7,      14, ..., 6999979, 6999986, 6999993])

In [10]:
l1 = range(1000000)
l2= range(1000000)

In [11]:
%time for i,j in zip(l1,l2):i+j
        

Wall time: 515 ms


In [12]:
a1=np.arange(1000000)
a2=np.arange(1000000)    

In [13]:
%time a1+a2

Wall time: 19.6 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [14]:
l1=range(1000000)
l2=range(1000000)
%time for i in range(len(l1)):l1[i]+l2[i]

Wall time: 1.24 s


In [16]:
np.zeros((8,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [19]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
np.arange(0,999,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [31]:
#list = [2,3.2,5.5,-6.4.-2.2,-2.4]
a = np.array([2,3.2,5.5,-6.4,-2.2,-2.4])
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4])

In [32]:
a[1]

3.2

In [33]:
a[1:4]

array([ 3.2,  5.5, -6.4])

In [2]:
import numpy as np

In [6]:
a=np.array([[2,3.2,5.5,-6.4,-2.2,-2.4],[1,22,4,0.1,5.3,-9],[3,1,2.1,21,1.1,-2]])
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [7]:
a[:,3]

array([-6.4,  0.1, 21. ])

In [8]:
a[1:4,0:4]

array([[ 1. , 22. ,  4. ,  0.1],
       [ 3. ,  1. ,  2.1, 21. ]])

In [41]:
a[1:,2]

array([4. , 2.1])

In [42]:
a[0]

array([ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4])

In [45]:
a[1]

array([ 1. , 22. ,  4. ,  0.1,  5.3, -9. ])

In [46]:
a[2]

array([ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ])

In [44]:
a[:,2]

array([5.5, 4. , 2.1])

In [47]:
a[:,0]

array([2., 1., 3.])

In [48]:
a[2,2]

2.1

In [49]:
a[0,1]

3.2

In [51]:
a[:,0:1]

array([[2.],
       [1.],
       [3.]])

In [52]:
a[:,1]

array([ 3.2, 22. ,  1. ])

In [53]:
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [57]:
[range(4),range(10,14)] #lazy evaluation



[range(0, 4), range(10, 14)]

In [65]:
arr=np.array([range(4),range(10,14)])
arr

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [66]:
arr.shape

(2, 4)

In [67]:
arr.size

8

In [68]:
arr.max()

13

In [70]:
arr.min()

0

In [76]:
arr.reshape(2,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [77]:
arr.reshape(2,2,2,order='F')

array([[[ 0,  2],
        [ 1,  3]],

       [[10, 12],
        [11, 13]]])

In [87]:
arr.transpose()

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [81]:
arr.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [83]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
np.arange(1,10)*3


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [86]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [88]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [89]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [3]:
import numpy as np

In [10]:
a=np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
c=a.reshape(2,4)
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
a+c

ValueError: operands could not be broadcast together with shapes (8,) (2,4) 

In [23]:
b=np.array((1,2))
b


array([1, 2])

In [7]:
a+b

ValueError: operands could not be broadcast together with shapes (8,) (2,) 

In [24]:
d=b.reshape(2,1)
d


array([[1],
       [2]])

In [138]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
c+d

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [17]:
a=[7,9,-9,8,3]


In [116]:
b=np.array(a)
b

array([ 7,  9, -9,  8,  3])

In [117]:
b%2==0

array([False, False, False,  True, False])

In [118]:
b[b%2==0]

array([8])

In [27]:
salary = np.array([-1, 100000, 200000, 300000])

In [28]:
np.where(salary<0,10000,salary)

array([ 10000, 100000, 200000, 300000])

In [29]:
np.where(salary<0,np.mean(salary),salary)

array([149999.75, 100000.  , 200000.  , 300000.  ])

In [30]:
salary.transpose()

array([    -1, 100000, 200000, 300000])

In [31]:
np.transpose(salary)

array([    -1, 100000, 200000, 300000])

In [32]:
np.cumsum(salary)

array([    -1,  99999, 299999, 599999], dtype=int32)

In [33]:
salary.t()/np.t(salary)

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [1]:
import numpy as np

In [4]:
x = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[14,15,16],[17,18,19]]])

In [5]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[14, 15, 16],
        [17, 18, 19]]])

In [8]:
d = np.arange(400).reshape(4,10,10)
d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [6]:
x = np.array([1,2,3,57,83,4])
x>5

array([False, False, False,  True,  True, False])

In [7]:
(x>5).sum()

2

In [8]:
t= x ==2
t.any()

True

In [9]:
import numpy as np

In [11]:
t= x>10
t.all()

False

In [19]:
jungle = np.array(['lion', 'cat', 'horse', 'lion', 'lion'])

In [20]:
(jungle == 'lion').sum()

3

In [21]:
a= jungle == 'donkey'

In [22]:
a.any()

False

In [23]:
print(x)

[ 1  2  3 57 83  4]


In [24]:
np.sort(x)

array([ 1,  2,  3,  4, 57, 83])

In [25]:
np.unique(jungle)# unique will give single time

array(['cat', 'horse', 'lion'], dtype='<U5')

In [27]:
np.save('data.npy',x)

In [28]:
np.load('data.npy')

array([ 1,  2,  3, 57, 83,  4])

In [31]:
x= np.random.randn(3,3)
x

array([[-0.19373654,  0.92823942,  1.05788418],
       [-1.06765487, -0.0241627 , -0.37376941],
       [ 0.34349879,  0.09819154, -0.48367965]])

In [35]:
np.save('random.npy',x)

In [36]:
s= np.load('random.npy')

In [37]:
s

array([[-0.19373654,  0.92823942,  1.05788418],
       [-1.06765487, -0.0241627 , -0.37376941],
       [ 0.34349879,  0.09819154, -0.48367965]])

In [38]:
s.shape

(3, 3)

In [39]:
p= np.random.randn(5,5)

In [40]:

p

array([[-0.07926633, -3.42703519,  0.78460016,  2.02819278,  0.25483214],
       [-1.08804788, -0.05280607, -0.04868606,  0.21034009,  1.00435301],
       [ 0.3204658 , -0.00715029,  1.84508612,  0.19223906,  0.16127883],
       [ 0.6256444 ,  0.2563091 , -0.0754043 ,  2.15899393, -0.82961611],
       [ 0.63865573, -2.44253216, -0.77672219, -2.70049581,  0.34611366]])

In [86]:
np.savez('numpy2.npz',a1=p,a2=x)

In [90]:
d = np.load('numpy2.npz')
d['a2']

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [71]:
x= np.arange(1,11).reshape(5,2)
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
y = np.arange(0,10,2)
y

array([0, 2, 4, 6, 8])

In [15]:
z= np.arange(3,10,3)
z

array([3, 6, 9])

In [16]:
np.savez('new9.npz',f1 = x, fz= y, f3 = z)

In [17]:
a=np.load('new9.npz')
#a['f1']

In [92]:
a.files

['f1', 'fz', 'f3']

# Linear algebra functions


In [115]:
a= np.random .randn(4,1) # no ofcolumns of first equals rows of second
b= np.random .randn(1,4)
print(a)
print(b)

[[0.00759824]
 [0.26271733]
 [0.06965609]
 [0.99372548]]
[[ 1.73123988  0.14974267 -0.25895819 -1.12935935]]


In [116]:
d= np.dot(a,b)
d

array([[ 1.31543749e-02,  1.13778062e-03, -1.96762634e-03,
        -8.58114260e-03],
       [ 4.54826710e-01,  3.93399930e-02, -6.80328043e-02,
        -2.96702267e-01],
       [ 1.20591406e-01,  1.04304891e-02, -1.80380160e-02,
        -7.86667594e-02],
       [ 1.72037717e+00,  1.48803103e-01, -2.57333355e-01,
        -1.12227315e+00]])

In [112]:
d= np.random .randn(4,4)
d

array([[-0.18222135, -0.12202613, -1.16106658,  0.65524451],
       [ 0.10966185, -2.31430617, -0.73010778, -0.11221753],
       [-0.28756021,  0.61725532, -0.88074025, -0.16502581],
       [-0.4906818 , -0.08537213,  0.02348559,  0.2687231 ]])

In [111]:
np.diag(d)

array([ 0.03392616,  0.07862041, -0.47594923,  1.36598972])

In [118]:
np.linalg.eig(d)  # principle componenet analysis

(array([ 0.00000000e+00, -1.08781680e+00, -1.09837525e-18, -4.33547689e-17]),
 array([[ 0.52527079,  0.00737512,  0.14304702,  0.02977974],
        [ 0.21699677,  0.25500283, -0.18435671, -0.98379443],
        [ 0.05753388,  0.06761069, -0.88710139, -0.17082234],
        [ 0.82078795,  0.96454547,  0.39824775, -0.04562257]]))

In [119]:
##bit.do/noman-islam

In [121]:
np.linalg.eig(d) # it is energy of vector
#determinant ki value eigen value hai...us se eigen vector banta ahi

(array([ 0.00000000e+00, -1.08781680e+00, -1.09837525e-18, -4.33547689e-17]),
 array([[ 0.52527079,  0.00737512,  0.14304702,  0.02977974],
        [ 0.21699677,  0.25500283, -0.18435671, -0.98379443],
        [ 0.05753388,  0.06761069, -0.88710139, -0.17082234],
        [ 0.82078795,  0.96454547,  0.39824775, -0.04562257]]))

# Pseudo random number generation

In [4]:
import numpy as np

In [5]:
x = np.random.gamma(shape = (2,2))
x

array([1.78678778, 4.78632476])

In [6]:
u = np.random.uniform(shape= (2,2))

TypeError: uniform() got an unexpected keyword argument 'shape'

In [9]:
x = np.random.randn(2,2)

In [15]:
x

array([[ 0.61245519, -1.60288842],
       [ 0.29737823, -1.57306092]])

In [13]:
np.random.seed(2)

In [19]:
np.random.seed(2)
np.random.randn(2,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081]])