In [2]:
import numpy as np

In [7]:
x = np.arange(1,11)
x.reshape((2,5),order = 'C')


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
x = np.arange(1,11)
       #[ 6,  7,  8,  9, 10]])
x.reshape((2,5),order = 'F')

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [12]:
p= np.random.randn(10000,2)
p

array([[ 0.12827835, -0.37721686],
       [-0.27185045,  1.55490206],
       [ 0.16224807,  0.41611696],
       ...,
       [ 0.46096867, -0.89600944],
       [ 0.40961774, -0.22265338],
       [-0.88670866,  0.9017423 ]])

In [10]:
c= p.reshape((2,-1))

array([[ 2.50041631, -0.24265487, -0.10543964, ..., -0.96894388,
         2.27104795, -0.17957248],
       [ 1.23309834,  0.04002503,  0.83049548, ...,  0.4724461 ,
        -0.0927064 ,  0.23281081]])

In [10]:
c.shape

(2, 100000)

In [14]:
a= np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [15]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [20]:
b=np.ravel(a)# here rival will give view  but does not create new array

In [14]:

b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
b[0]= -1

In [23]:
a

array([[-1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [24]:
a

array([[-1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [19]:
c= a.flatten()#flatten  doesnt cahnge in the prvious instead it will make a new copy

In [20]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
c[0] = -1

In [22]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [24]:
a = np.arange(1,11). reshape(2,5)

In [25]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
b = np.arange(11,31).reshape(4,5)
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
np.concatenate((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [33]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
x= np.arange(1,11).reshape(5,2)     
x# horizonatl stacking

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [40]:
y = np.arange(11,31).reshape(5,4)
y

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [41]:
np.concatenate((x,y),axis = 1)

array([[ 1,  2, 11, 12, 13, 14],
       [ 3,  4, 15, 16, 17, 18],
       [ 5,  6, 19, 20, 21, 22],
       [ 7,  8, 23, 24, 25, 26],
       [ 9, 10, 27, 28, 29, 30]])

In [43]:
np.append??

In [44]:
np.hstack((x,y))

array([[ 1,  2, 11, 12, 13, 14],
       [ 3,  4, 15, 16, 17, 18],
       [ 5,  6, 19, 20, 21, 22],
       [ 7,  8, 23, 24, 25, 26],
       [ 9, 10, 27, 28, 29, 30]])

In [56]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [57]:
y

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [60]:
np.c_[x,y]   #np.r_

array([[ 1,  2, 11, 12, 13, 14],
       [ 3,  4, 15, 16, 17, 18],
       [ 5,  6, 19, 20, 21, 22],
       [ 7,  8, 23, 24, 25, 26],
       [ 9, 10, 27, 28, 29, 30]])

In [63]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [64]:
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [66]:
np.r_[a,b]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [51]:
y

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [69]:
np.split(y,[3],axis = 1)

[array([[11, 12, 13],
        [15, 16, 17],
        [19, 20, 21],
        [23, 24, 25],
        [27, 28, 29]]), array([[14],
        [18],
        [22],
        [26],
        [30]])]

In [67]:
f= np.arange(1,10)
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.split(f,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]