In [3]:
list1 = range(1000000)


In [5]:
%time for i in list1: i*2

Wall time: 421 ms


In [6]:
import numpy as np


In [7]:
arr = np.arange(1000000)

In [9]:
%time arr*2

Wall time: 7 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [11]:
data = np.random.randn(2,3)
data

array([[-1.72819533, -0.14634864,  1.22561892],
       [ 0.87936026, -1.06035374,  0.3461997 ]])

In [12]:
data.shape

(2, 3)

In [13]:
data.ndim

2

In [14]:
data.dtype

dtype('float64')

In [15]:
data + data

array([[-3.45639067, -0.29269728,  2.45123784],
       [ 1.75872052, -2.12070748,  0.69239939]])

In [16]:
data *2

array([[-3.45639067, -0.29269728,  2.45123784],
       [ 1.75872052, -2.12070748,  0.69239939]])

In [25]:
np.zeros([2,3,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [26]:
np.ones([1,2])

array([[1., 1.]])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
data.astype(np.int64)

array([[-1,  0,  1],
       [ 0, -1,  0]], dtype=int64)

In [47]:
import numpy as np

In [22]:
arr =np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr1 = np.array([[2,3,1], [1,2,3]])
arr1


array([[2, 3, 1],
       [1, 2, 3]])

In [27]:
x=  arr*arr1
x

array([[ 2,  6, 12],
       [ 4, 10, 18]])

# 1D array 

In [66]:
list11 = [1,2,3,4,8]

In [67]:
x= np.array(list11)
x

array([1, 2, 3, 4, 8])

In [68]:
x[2:5]


array([3, 4, 8])

In [72]:
x[2:5] = 10
x

array([ 1,  2, 10, 10, 10])

In [73]:
x

array([ 1,  2, 10, 10, 10])

In [101]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr[1,2]

6

In [122]:
x=arr[:,1]
x

array([2, 5])

In [123]:
x.shape

(2,)

In [124]:
y = arr[:,:1]
y

array([[1],
       [4]])

In [125]:
y.shape

(2, 1)

In [112]:
arr[:,:1]

array([[1],
       [4]])

In [113]:
arr.shape

(2, 3)

# 3D array 

In [106]:
new_arr= np.array([[[1,2,3, 4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [107]:
new_arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [108]:
new_arr[0,1,2]

7

In [104]:
new_arr[0,1]= 0
new_arr

array([[[ 1,  2,  3,  4],
        [ 0,  0,  0,  0]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [131]:
new =np.array([[1,2,3],[4,5,6],[7,8,9]])

In [132]:
new

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
new[:2,1:]

array([[2, 3],
       [5, 6]])

In [137]:
x=new[2,:]
x

array([7, 8, 9])

In [142]:
x.ndim

1

In [140]:
y=new[2:,:]
y

array([[7, 8, 9]])

In [143]:
y.ndim

2