# why numpy... because of screen
Numpy...Numeric Python

In [1]:
l = range(1000000)

In [2]:
%time for i in l:    i*7
    

Wall time: 278 ms


In [4]:
#range returns list while arange returns array.

In [7]:
import numpy as np

In [8]:
l=np.arange(1000000)

In [9]:
%time l*7

Wall time: 0 ns


array([      0,       7,      14, ..., 6999979, 6999986, 6999993])

In [10]:
l1 = range(1000000)
l2= range(1000000)

In [11]:
%time for i,j in zip(l1,l2):i+j
        

Wall time: 515 ms


In [12]:
a1=np.arange(1000000)
a2=np.arange(1000000)    

In [13]:
%time a1+a2

Wall time: 19.6 ms


array([      0,       2,       4, ..., 1999994, 1999996, 1999998])

In [14]:
l1=range(1000000)
l2=range(1000000)
%time for i in range(len(l1)):l1[i]+l2[i]

Wall time: 1.24 s


In [16]:
np.zeros((8,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [18]:
np.array([2,4,6,8])

array([2, 4, 6, 8])

In [19]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
np.arange(0,999,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [31]:
#list = [2,3.2,5.5,-6.4.-2.2,-2.4]
a = np.array([2,3.2,5.5,-6.4,-2.2,-2.4])
a

array([ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4])

In [32]:
a[1]

3.2

In [33]:
a[1:4]

array([ 3.2,  5.5, -6.4])

In [38]:
a=np.array([[2,3.2,5.5,-6.4,-2.2,-2.4],[1,22,4,0.1,5.3,-9],[3,1,2.1,21,1.1,-2]])
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [39]:
a[:,3]

array([[ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [40]:
a[1:4,0:4]

array([[ 1. , 22. ,  4. ,  0.1],
       [ 3. ,  1. ,  2.1, 21. ]])

In [41]:
a[1:,2]

array([4. , 2.1])

In [42]:
a[0]

array([ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4])

In [45]:
a[1]

array([ 1. , 22. ,  4. ,  0.1,  5.3, -9. ])

In [46]:
a[2]

array([ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ])

In [44]:
a[:,2]

array([5.5, 4. , 2.1])

In [47]:
a[:,0]

array([2., 1., 3.])

In [48]:
a[2,2]

2.1

In [49]:
a[0,1]

3.2

In [51]:
a[:,0:1]

array([[2.],
       [1.],
       [3.]])

In [52]:
a[:,1]

array([ 3.2, 22. ,  1. ])

In [53]:
a

array([[ 2. ,  3.2,  5.5, -6.4, -2.2, -2.4],
       [ 1. , 22. ,  4. ,  0.1,  5.3, -9. ],
       [ 3. ,  1. ,  2.1, 21. ,  1.1, -2. ]])

In [57]:
[range(4),range(10,14)] #lazy evaluation



[range(0, 4), range(10, 14)]

In [65]:
arr=np.array([range(4),range(10,14)])
arr

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [66]:
arr.shape

(2, 4)

In [67]:
arr.size

8

In [68]:
arr.max()

13

In [70]:
arr.min()

0

In [76]:
arr.reshape(2,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]]])

In [77]:
arr.reshape(2,2,2,order='F')

array([[[ 0,  2],
        [ 1,  3]],

       [[10, 12],
        [11, 13]]])

In [87]:
arr.transpose()

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [81]:
arr.ravel()

array([ 0,  1,  2,  3, 10, 11, 12, 13])

In [83]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [85]:
np.arange(1,10)*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [86]:
np.arange(3,30,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [88]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [89]:
np.linspace(0,1,8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [132]:
a=np.arange(1,9)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [133]:
c=a.reshape(2,4)
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
b=np.array((1,2))
b

array([1, 2])

In [136]:
a+b

ValueError: operands could not be broadcast together with shapes (8,) (2,) 

In [137]:
d=b.reshape(2,1)
d

array([[1],
       [2]])

In [138]:
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [144]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [140]:
c+d

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [115]:
a=[7,9,-9,8,3]

In [116]:
b=np.array(a)
b

array([ 7,  9, -9,  8,  3])

In [117]:
b%2==0

array([False, False, False,  True, False])

In [118]:
b[b%2==0]

array([8])

In [122]:
salary = np.array([-1, 100000, 200000, 300000])

In [123]:
np.where(salary<0,10000,salary)

array([ 10000, 100000, 200000, 300000])

In [124]:
np.where(salary<0,np.mean(salary),salary)

array([149999.75, 100000.  , 200000.  , 300000.  ])

In [127]:
salary.transpose()

array([    -1, 100000, 200000, 300000])

In [125]:
np.transpose(salary)

array([    -1, 100000, 200000, 300000])

In [128]:
np.cumsum(salary)

array([    -1,  99999, 299999, 599999], dtype=int32)

In [130]:
salary.t()/np.t(salary)

AttributeError: 'numpy.ndarray' object has no attribute 't'